site_name: SparkMart Documentation
site_description: Blockchain‑Enabled Green & Secure Logistics
site_author: SparkMart Team
site_url: https://sparkmart.github.io/docs

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - social
  - panzoom:
      include_selectors:
        - ".mermaid"
      key: "ctrl" # Hold Ctrl + scroll/drag
      hint_location: top
      always_show_hint: true
      full_screen: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Resouces: features/resources.md
  # - API Reference:
  # - Authentication: api/authentication.md
  # - Endpoints: api/endpoints.md
  - Support:
      - FAQ: support/faq.md
      - Contact: support/contact.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vibeguide-ai
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vibeguide_ai
    - icon: fontawesome/solid/globe
      link: https://vibeguide.ai

copyright: Copyright &copy; 2025 SparkMart
